test:
  start_snr: 5
  correct_threshold: 2
  minimum_threshold: -40
  incorrect_threshold: 1
  step_size: [5, 3, 1]
  reversal_limit: 10
  record_save_dir: "records"
  hearing-test:
    DIN:
      noise:
        type: babble #[white, babble]
        src: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/audio_processing/noise/babble.wav"
      stimuli-recordings-natural: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/digit_recordings/natural/22k"
      stimuli-recordings-tts: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/digit_recordings/tts/22k"

    ASL:
      noise:
        type: babble #[white, babble]
        src: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/audio_processing/noise/babble.wav"
      stimuli-recordings-natural: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/ASL/natural/22k/test"
      stimuli-recordings-tts: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/ASL/tts/mello"
    FAAF:
      noise:
        type: babble #[white, babble]
        src: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/audio_processing/noise/babble.wav"
      stimuli-recordings-natural: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/FAAF/natural"
      stimuli-recordings-tts: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/ASL/tts/mello"

response_capturing: cli #[cli, asr]
vocalization_mode: recorded #[tts, recorded]
test_name: din #[din, asl]

ml:
  asr_type: wav2vec2 #[SpeechBrain, SimpleASR,whisper, wav2vec2]
  asr_source: "speechbrain/asr-wav2vec2-commonvoice-en" #["speechbrain/asr-wav2vec2-commonvoice-en","speechbrain/asr-crdnn-rnnlm-librispeech"]
  asr_save_dir: "models/asr/asr-wav2vec2-commonvoice-en" #["models/asr/asr-wav2vec2-commonvoice-en","models/asr/asr-crdnn-rnnlm-librispeech"]
