test:
  start_snr: 5
  correct_threshold: 2
  minimum_threshold: -40
  incorrect_threshold: 1
  step_size: [5, 3, 1]
  reversal_limit: 10
  record_save_dir: "records"
  hearing-test:
    DIN:
      noise:
        type: babble #[white, babble]
        src: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/audio_processing/noise/babble.wav"
      stimuli-recordings-natural: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/digit_recordings/natural/22k"
      stimuli-recordings-tts: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/digit_recordings/tts/22k"

    ASL:
      noise:
        type: babble #[white, babble]
        src: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/ASL/adjusted/natural/22k/speech_shaped_noise_ASL_natural.wav"
        src-tts: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/ASL/adjusted/tts/speech_shaped_noise_ASL_tts.wav"
        src_tts_low_pass: ""
        src_tts_low_pass_modulation_matched: ""
        src_tts_modulation_matched: ""

        # src-tts: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/ASL/adjusted/tts/speech_shaped_noise_low_pass_8k.wav"

      stimuli-recordings-natural: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/ASL/adjusted/natural/22k/test"
      stimuli-recordings-tts: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/ASL/adjusted/tts/mello/test"
      stimuli_recordings_tts_low_pass: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/ASL/adjusted/tts/lowpass_filtered/test"
      stimuli_recordings_tts_low_pass_modulation_matched: "/Users/user/Documents/"
      stimuli_recordings_tts_modulation_matched: "/Users/user/Documents/"

    FAAF:
      noise:
        type: babble #[white, babble]
        src: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/FAAF/adjusted/speech_shaped_noise_FAAF_adjusted.wav"
      stimuli-recordings-natural: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/FAAF/adjusted/natural"
    CHAT:
      noise:
        type: babble #[white, babble]
        src-tts: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/CHAT/adjusted/speech_shaped_noise_CHAT.wav"
      stimuli-recordings-tts: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/media/CHAT/adjusted/tts"

response_capturing: cli #[cli, asr]
vocalization_mode: recorded #[tts, recorded]
test_name: din #[din, asl]
test_mode: test #[test, practice]
ml:
  asr_type: whisper #[SpeechBrain, SimpleASR,whisper, wav2vec2]
  asr_source: "speechbrain/asr-wav2vec2-commonvoice-en" #["speechbrain/asr-wav2vec2-commonvoice-en","speechbrain/asr-crdnn-rnnlm-librispeech"]
  asr_save_dir: "models/asr/asr-wav2vec2-commonvoice-en" #["models/asr/asr-wav2vec2-commonvoice-en","models/asr/asr-crdnn-rnnlm-librispeech"]
